Feature/contract api server controller
input-output-hk/smart-contract-backend pull request #58
Opened 2019-05-10 04:58 UTC by rhyslbw

Introduces the `ContractApiServerController`, and concept of _engine client_. Also adds a new test bundle to target the `StubEngineClient`. This will probably get refactored away now we have an interface for the clients. Deferring this as it's not critical

2019-05-10 06:04 UTC, Sam-Jeston requested changes

2019-05-10 06:04 UTC, Sam-Jeston commented on src/server/application/ContractApiServerController.ts
> +      if (servers.has(contractAddress)) return true
Might as well do the `servers.has` return check prior to getting an available port.

2019-05-10 06:04 UTC, Sam-Jeston commented on src/server/application/ContractApiServerController.ts
> +      const serverInfo = await new ApolloServer({
I think we should gracefully handle the error here. As much as its unlikely, it is possible that the port you just queried is no longer available by the time the server goes to boot.

2019-05-10 06:04 UTC, Sam-Jeston commented on src/server/application/PortManager.ts
> +      const portAllocation = {
Possibly the above is cleaner as

```
const portNumber = size === 0
 ? range.lower
 : (await repository.getLast()).portNumber + 1
```

I prefer assigning to a const through a ternary. But this is subjective, feel free to leave it

2019-05-10 06:04 UTC, Sam-Jeston commented on src/server/core/errors/AllPortsAllocated.ts
> +    this.message = `All ports in the range ${rangeString(range)} have all been allocated`
```suggestion
    this.message = `All ports in the range ${rangeString(range)} have been allocated`
```

2019-05-10 06:04 UTC, Sam-Jeston commented on src/server/infrastructure/engine_clients/StubEngineClient.ts
> +export function StubEngineClient (): EngineClient {
👍

2019-05-10 08:58 UTC, rhyslbw commented on src/server/application/PortManager.ts
> +      const portAllocation = {
Agree, I'll update

2019-05-10 08:58 UTC, rhyslbw commented on src/server/application/ContractApiServerController.ts
> +      const serverInfo = await new ApolloServer({
Good catch

2019-05-14 00:02 UTC, Sam-Jeston approved these changes
👍

2019-05-14 00:02 UTC, merged