Chore/file reorg
input-output-hk/smart-contract-backend pull request #72
Opened 2019-05-31 06:16 UTC by rhyslbw

See commit log

2019-05-31 06:55 UTC, Sam-Jeston requested changes
Just minor naming thoughts.

Also please remove this from the git cache and update .gitignore: src/execution_engine/routes.ts

2019-05-31 06:55 UTC, Sam-Jeston commented on src/lib/expressPromises.ts
> +export const expressPromises = {
I think this could be named better

Maybe `expressListenEventPromiseHandler`

2019-05-31 06:55 UTC, Sam-Jeston commented on src/lib/httpPromises.ts
> +export const httpPromises = {
Same here

2019-05-31 08:41 UTC, rhyslbw commented
The change to gitignore was committed in https://github.com/input-output-hk/smart-contract-backend/pull/72/commits/729ce0bc2104037bc459c3318f1e63e6f2c6628e

2019-06-02 22:59 UTC, Sam-Jeston approved these changes
💯

2019-06-02 22:59 UTC, merged